CREATE TABLE `user` (
 `userID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 `city` VARCHAR(50) NOT NULL,
 `country` VARCHAR(50) NOT NULL,
 `email` VARCHAR(50) NOT NULL UNIQUE KEY,
 `name` VARCHAR(50) NOT NULL
);

CREATE TABLE `song` (
`songID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`date` DATE NOT NULL,
`songName` VARCHAR(50) NOT NULL
);

CREATE TABLE `artist` (
`artistID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(50) NOT NULL,
`followCount` INT NOT NULL
);

CREATE TABLE `genre` (
 `genreID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 `genreName` VARCHAR(50) NOT NULL
);

CREATE TABLE `userSong` (
`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`dateAdded` DATE NOT NULL,
`listenCount` INT NOT NULL,
`songID` INT NOT NULL,
`userID` INT NOT NULL,
FOREIGN KEY (`songID`) REFERENCES `song`(`songID`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
FOREIGN KEY (`userID`) REFERENCES `user`(`userID`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
UNIQUE KEY `userSong` (`songID`, `userID`)
);

CREATE TABLE `artistSong` (
`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
`artistID` INT NOT NULL,
`songID` INT NOT NULL,
FOREIGN KEY (`artistID`) REFERENCES `artist`(`artistID`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
FOREIGN KEY (`songID`) REFERENCES `song`(`songID`)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
UNIQUE KEY `artistSong` (`artistID`, `songID`)
);

CREATE TABLE `userFollow` (
`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`userID` INT NOT NULL,
`artistID` INT NOT NULL,
FOREIGN KEY (`userID`) REFERENCES `user`(`userID`),
FOREIGN KEY (`artistID`) REFERENCES `artist`(`artistID`),
UNIQUE KEY `userFollow` (`userID`, `artistID`)
);

CREATE TABLE `genreSong` (
`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`songID` INT NOT NULL,
`genreID` INT NOT NULL,
FOREIGN KEY (`songID`) REFERENCES `song` (`songID`),
FOREIGN KEY (`genreID`) REFERENCES `genre`(`genreID`),
UNIQUE KEY `genereSong` (`songID`, `genreID`)
);
